PATIENT = "patient"
DOCTOR = "doctor"
PERSON = "person"
DOCTOR_PATIENT = "doctor_patient"
MEDICINE = "medicine"
REGION = "region"
DISTRICT = "district"
CITY = "city"
ALLERGY = "allergy"
PATIENT_ALLERGY = "patient_allergy"
EXAMINATION = "examination"
RECIPE = "recipe"
RECIPE_MEDICINE = "recipe_medicine"
PATIENT_INSURANCE = "patient_insurance"
INSURANCE = "insurance"

T_INSURANCE_HISTORY = "t_rec_insurance_history"
T_INSURANCE_TABLE = "t_insurance_history"

T_SYMPTOM = "t_symptom"
T_SYMPTOM_TABLE = "t_symptoms_table"

T_TREATMENT = "t_treatment"
T_TREATMENT_TABLE = "t_treatment_table"
